flaskr/main/models/__init__.py
from .models import (
    User,
    Information,
    Mail,
    Calendar,
    SlackChannel,
    SlackChannelMember,
    SlackMessage,
    ZoomAccessToken,
    ZoomMeeting,
    Project,
    Importance,
)

__all__ = [
    User,
    Information,
    Mail,
    Calendar,
    SlackChannel,
    SlackChannelMember,
    SlackMessage,
    ZoomAccessToken,
    ZoomMeeting,
    Project,
    Importance,
]

flaskr/main/models/models.py
from sqlalchemy import func, CheckConstraint, UniqueConstraint
from flaskr.database import db
from datetime import datetime


class User(db.Model):
    """
    作成者: kazu
    概要: 従業員識別情報を保存しているテーブル
    """
    __tablename__ = 'users'
    __table_args__ = (
        CheckConstraint('updated_at >= created_at'),  # チェック制約
    )
    id = db.Column(db.Integer, primary_key=True)  # 主キー
    slack_id = db.Column(db.String(20), index=True, unique=True)
    gmail = db.Column(db.String(50), index=True, unique=True)
    created_at = db.Column(db.DateTime)
    updated_at = db.Column(db.DateTime)
    mail = db.relationship('Mail', backref='user', lazy=True)
    information = db.relationship('Information', backref='user', lazy=True)
    calendar = db.relationship('Calendar', backref='user', lazy=True)
    slack_channel_member = db.relationship('SlackChannelMember', backref='user', lazy=True)
    slack_message = db.relationship('SlackMessage', backref='user', lazy=True)
    zoom_access_token = db.relationship('ZoomAccessToken', backref='user', lazy=True)
    zoom_meeting = db.relationship('ZoomMeeting', backref='user', lazy=True)
    zoom_participant = db.relationship('ZoomParticipant', backref='user', lazy=True)

    def __init__(self, slack_id, gmail, created_at, updated_at):
        self.slack_id = slack_id
        self.gmail = gmail
        self.created_at = created_at
        self.updated_at = updated_at

    def __str__(self):
        return f"id = {self.id}, slack_id={self.slack_id}, gmail={self.gmail}, created_at={self.created_at}, updated_at={self.updated_at}"

    @classmethod
    def select_users(cls):
        raw_data = db.session.query(cls).with_entities(cls.id, cls.slack_id, cls.gmail).all()
        data = {}
        data['id'] = raw_data[0]
        data['slack_id'] = raw_data[1]
        data['gmail'] = raw_data[2]
        return data

    @classmethod
    def select_users_by_id(cls, user_id):
        return db.session.query(cls).with_entities(cls.id, cls.slack_id, cls.gmail).filter(cls.id == user_id).first()

    @classmethod
    def insert_user(self, data):
        target = User(gmail=data['gmail'], slack_id=data['slack_id'], created_at=datetime.now(),
                      updated_at=datetime.now())
        db.session.add(target)
        db.session.commit()

    @classmethod
    def insert_gmail(self, gmail):
        target = User(gmail=gmail, slack_id=None, created_at=datetime.now(), updated_at=datetime.now())
        db.session.add(target)
        db.session.commit()

    @classmethod
    def update_user(cls, user_id, information_data):
        user = db.session.query(cls).filter(cls.id == user_id).first()
        if 'gmail' in information_data:
            user.gmail = information_data['gmail']
        if 'slack_id' in information_data:
            user.slack_id = information_data['slack_id']
        user.updated_at = datetime.now()
        db.session.commit()

    @classmethod
    def check_user_mail(cls, gmail):
        return db.session.query(cls).with_entities(cls.id).filter(cls.gmail == gmail).first()

    @classmethod
    def check_user_slack_id(cls, slack_id):
        return db.session.query(cls).with_entities(cls.id).filter(cls.slack_id == slack_id).first()

    @classmethod
    def delete_by_id(cls, user_id):
        db.session.query(cls).filter(cls.id == user_id).delete()
        db.session.commit()


class Project(db.Model):
    """
        作成者: kazu
        概要: コミュニティ内で運用されているプロジェクト名を保存しているテーブル
    """
    __tablename__ = 'projects'
    __table_args__ = (
        CheckConstraint('updated_at >= created_at'),  # チェック制約
    )
    id = db.Column(db.Integer, primary_key=True, autoincrement=True)  # 主キー
    name = db.Column(db.String(50), index=True, nullable=False)
    created_at = db.Column(db.DateTime, nullable=False, default=datetime.now)
    updated_at = db.Column(db.DateTime, nullable=False, default=datetime.now, onupdate=datetime.now)
    importance = db.relationship('Importance', backref='projects', lazy=True)

    def __init__(self, name, created_at, updated_at):
        self.name = name
        self.created_at = created_at
        self.updated_at = updated_at

    def __str__(self):
        return f"id = {self.id}, name = {self.name}, create_at={self.created_at}, update_at={self.updated_at} "

    @classmethod
    def select_project(cls):
        raw_data = db.session.query(cls).with_entities(cls.id, cls.name).all()
        result_data = []
        for r in raw_data:
            data = {'id': r[0], 'name': r[1]}
            result_data.append(data)
        return result_data

    @classmethod
    def select_project_by_name(cls, name):
        data = db.session.query(cls).with_entities(cls.id).filter(cls.name == name).first()
        return data


class Importance(db.Model):
    """
        作成者: kazu
        概要: 各プロジェクトごとに設定された各Webアプリケーションの重要度を保存するテーブル
    """
    __tablename__ = 'projects_importance'
    __table_args__ = (
        CheckConstraint('updated_at >= created_at'),  # チェック制約
    )
    id = db.Column(db.Integer, primary_key=True, autoincrement=True)  # 主キー
    project_id = db.Column(db.Integer, db.ForeignKey('projects.id'), nullable=False)
    service = db.Column(db.String(50), nullable=False)
    importance = db.Column(db.Integer, nullable=False)
    created_at = db.Column(db.DateTime, nullable=False, default=datetime.now)
    updated_at = db.Column(db.DateTime, nullable=False, default=datetime.now, onupdate=datetime.now)

    def __init__(self, project_id, service, importance, created_at, updated_at):
        self.project_id = project_id
        self.service = service
        self.importance = importance
        self.created_at = created_at
        self.updated_at = updated_at

    def __str__(self):
        return f"id = {self.id}, project_id = {self.project_id}, service = {self.service}, importance = {self.importance}, create_at={self.created_at}, update_at={self.updated_at} "

    @classmethod
    def select_importance(cls, project_id):
        data = db.session.query(cls).with_entities(cls.service, cls.importance).filter(cls.project_id == project_id).all()
        result_data = {}
        for d in data:
            result_data[d[0]] = d[1]
        return result_data

    @classmethod
    def update_importance(cls, values):
        target = db.session.query(cls).filter(cls.project_id == values['project_id']).filter(
            cls.service == 'mail').first()
        target.importance = values['importance']['mail']
        target.updated_at = datetime.now()
        db.session.add(target)

        target = db.session.query(cls).filter(cls.project_id == values['project_id']).filter(
            cls.service == 'schedule').first()
        target.importance = values['importance']['schedule']
        target.updated_at = datetime.now()
        db.session.add(target)

        target = db.session.query(cls).filter(cls.project_id == values['project_id']).filter(
            cls.service == 'slack').first()
        target.importance = values['importance']['slack']
        target.updated_at = datetime.now()
        db.session.add(target)

        target = db.session.query(cls).filter(cls.project_id == values['project_id']).filter(
            cls.service == 'zoom').first()
        target.importance = values['importance']['zoom']
        target.updated_at = datetime.now()
        db.session.add(target)

        db.session.commit()


class Information(db.Model):
    """
        作成者: kazu
        概要: 従業員情報を保存しているテーブル
    """
    __tablename__ = 'information'
    __table_args__ = (
        CheckConstraint('updated_at >= created_at'),  # チェック制約
    )
    id = db.Column(db.Integer, primary_key=True, autoincrement=True)  # 主キー
    user_id = db.Column(db.Integer, db.ForeignKey('users.id'), nullable=False)
    name = db.Column(db.String(20), index=True)
    department = db.Column(db.String(30), index=True)
    birthday = db.Column(db.DateTime)
    sex = db.Column(db.String(5))
    created_at = db.Column(db.DateTime, nullable=False, default=datetime.now)
    updated_at = db.Column(db.DateTime, nullable=False, default=datetime.now, onupdate=datetime.now)

    def __init__(self, user_id, name, department, birthday, sex, created_at, updated_at):
        self.user_id = user_id
        self.name = name
        self.department = department
        self.birthday = birthday
        self.sex = sex
        self.created_at = created_at
        self.updated_at = updated_at

    def __str__(self):
        return f"id = {self.id}, user_id = {self.user_id}, name = {self.name}, department = {self.department}, birthday = {self.birthday}, sex = {self.sex}, create_at={self.created_at}, update_at={self.updated_at} "

    @classmethod
    def select_information(cls, user_id):
        raw_data = cls.query.with_entities(
            cls.id, cls.user_id, cls.name, cls.department, cls.birthday, cls.sex
        ).filter(cls.user_id == user_id).first()
        data = {}
        data['id'] = raw_data[0]
        data['user_id'] = raw_data[1]
        data['name'] = raw_data[2]
        data['department'] = raw_data[3]
        data['birthday'] = raw_data[4].date()
        data['sex'] = raw_data[5]
        return data

    @classmethod
    def insert_information(self, user_id, information_data):
        target = Information(user_id=user_id, name=information_data['name'], department=information_data['department'],
                             birthday=information_data['birthday'], sex=information_data['sex'],
                             created_at=datetime.now(), updated_at=datetime.now())
        db.session.add(target)
        db.session.commit()

    @classmethod
    def update_information(cls, user_id, information_data):
        information = db.session.query(cls).filter(cls.user_id == user_id).first()
        if 'name' in information_data:
            information.name = information_data['name']
        if 'department' in information_data:
            information.department = information_data['department']

flaskr/main/views.py
import json
import re
import os
import mysql.connector as mydb
import pymysql
import time
from flask import Blueprint, render_template, request
from flaskr.database import db
from flaskr.main.functions import project_analysis
from datetime import datetime
from flaskr.database import connect_db
from flaskr.main.models import (
    User,
    Information,
    Mail,
    Calendar,
    SlackChannelMember,
    SlackChannel,
    SlackMessage,
    ZoomMeeting,
    Project,
    Importance
)

main_bp = Blueprint('main', __name__, template_folder='templates')


@main_bp.route('/')
def top_menu():
    """
        作成者: kazu
        概要: トップ画面
    """
    user_data = None
    while not user_data:
        print("while")
        try:
            users_data = db.session.query(User, Information).join(Information, User.id == Information.user_id).with_entities(
                User.id, User.gmail, User.slack_id, Information.name, Information.department).all()
            db.session.commit()
            db.session.close()
            break
        except Exception:
            print('リロード')
            time.sleep(5)
            continue

    users = []
    for user_data in users_data:
        user = {}
        user['id'] = user_data[0]
        user['mail'] = user_data[1]
        user['slack_id'] = user_data[2]
        user['name'] = user_data[3]
        user['department'] = user_data[4]
        users.append(user)

    projects = Project.select_project()

    return render_template(
        'main/top.html',
        users=users,
        projects=projects
    )


@main_bp.route('/user')
def user_detail():
    """
        作成者: kazu
        概要: 従業員情報を表示する画面
    """
    user_id = request.args.get('id')
    status = 0
    while status == 0:
        try:
            user = User.select_users_by_id(user_id)
            information = Information.select_information(user_id)
            mail = Mail.select_mail(user_id)
            schedule = Calendar.select_schedule_id(user_id)
            slack_channel = db.session.query(SlackChannelMember, SlackChannel).join(SlackChannel, SlackChannelMember.channel_id == SlackChannel.id).with_entities(
                SlackChannelMember.user_id, SlackChannelMember.channel_id, SlackChannel.name).filter(SlackChannelMember.user_id==user_id).all()
            print(slack_channel)
            db.session.commit()
            db.session.close()
            slack_message = db.session.query(SlackMessage, SlackChannel).join(SlackChannel, SlackMessage.channel_id == SlackChannel.id).with_entities(
                SlackMessage.id, SlackMessage.event_id, SlackMessage.event_type, SlackMessage.event_time, SlackMessage.message_time, SlackMessage.file_id, SlackMessage.text, SlackMessage.reaction, SlackChannel.name).filter(SlackMessage.user_id==user_id).all()
            db.session.commit()
            db.session.close()
            zoom_meeting = ZoomMeeting.select_meeting(user_id)
            status = 1
        except Exception:
            time.sleep(5)
            continue


    return render_template(
        'main/user_detail.html',
        user=user,
        information=information,
        mail=mail,
        schedule=schedule,
        slack_channel=slack_channel,
        slack_message=slack_message,
        zoom_meeting=zoom_meeting,
    )

@main_bp.route('/project')
def project_detail():
    """
        作成者: kazu
        概要: 各プロジェクト毎の情報を表示する画面
    """
    project_name = request.args.get('name')
    return project_detail_load(project_name)


def project_detail_load(project_name):
    """
        作成者: kazu
        概要: 各プロジェクト毎の情報を表示する関数
    """
    status = 0
    while status == 0:
        try:
            analysis = project_analysis.analytics(project_name)
            status = 1
        except Exception:
            time.sleep(5)
            continue

    names = []
    names_str = ""
    gmail_data = []
    schedule_data = []

    total_mail_count = 0
    total_schedule_count = 0
    total_slack_count = 0
    total_zoom_count = 0

    for i in analysis['user_id']:
        information = Information.select_information(i)
        names_updated = []
        names.append(information['name'])
        gmail_data.append(analysis[i]['mail_count'])
        schedule_data.append(analysis[i]['schedule_count'])
        total_mail_count += analysis[i]['mail_count']
        total_schedule_count += analysis[i]['schedule_count']
        total_slack_count += analysis[i]['slack_count']
        total_zoom_count += analysis[i]['zoom_count']

    for i in analysis['user_id']:
        analysis[i]['contribution_mail'] = 0
        analysis[i]['contribution_schedule'] = 0
        analysis[i]['contribution_slack'] = 0
        analysis[i]['contribution_zoom'] = 0
        if total_mail_count != 0:
            analysis[i]['contribution_mail'] = '{:.1f}'.format((analysis[i]['mail_count']/total_mail_count)*100)
        if total_schedule_count != 0:
            analysis[i]['contribution_schedule'] = '{:.1f}'.format((analysis[i]['schedule_count'] / total_schedule_count) * 100)
        if total_slack_count != 0:
            analysis[i]['contribution_slack'] = '{:.1f}'.format((analysis[i]['slack_count'] / total_slack_count) * 100)
        if total_zoom_count != 0:
            analysis[i]['contribution_zoom'] = '{:.1f}'.format((analysis[i]['zoom_count'] / total_zoom_count) * 100)

    project_id = Project.select_project_by_name(project_name)[0]
    importance = Importance.select_importance(project_id)
    analysis = project_analysis.project_contribution(project_id, analysis)

    data = {}
    data['names'] = names
    data['gmail_data'] = gmail_data
    data['schedule_data'] = schedule_data

    names_str = str(names)[1:-1].replace("'", "")

    return render_template(
        'main/project_detail.html',
        project_name=project_name,
        analysis=analysis,
        data=data,
        names_str=names_str,
        importance=importance
    )


@main_bp.route('/project', methods=['POST'])
def project_importance_update():
    """
        作成者: kazu
        概要: 各プロジェクト毎に設定する各ウェブアプリケーションの重要度をフォームから更新する関数
    """
    project_name = request.args.get('name')
    values = {
        'project_id': Project.select_project_by_name(project_name)[0],
        'importance': {
            'mail': request.form.get('mail'),
            'schedule': request.form.get('schedule'),
            'slack': request.form.get('slack'),
            'zoom': request.form.get('zoom')
        }
    }
    Importance.update_importance(values)
    return project_detail_load(project_name)

flaskr/templates/main/project_detail.html
{% extends "base.html" %}
{% block title %}
    プロジェクト詳細
{% endblock %}
{% block content %}
    <a href="{{url_for('main.top_menu')}}">トップメニュー</a>
    <h1>プロジェクト情報</h1>
    <h2>{{ project_name }}</h2>

     <table border="1">
        <tr>
            <th>従業員ID</th>
            <th>名前</th>
            <th>部署</th>
            <th>全体貢献度</th>
            <th>メール</th>
            <th>スケジュール</th>
            <th>スラックメッセージ</th>
            <th>ズームミーティング</th>
        </tr>
        {% for a in analysis.user_id %}
            <tr>
                <th>{{ a }}</th>
                <th>{{ analysis[a]['name'] }}</th>
                <th>{{ analysis[a]['department'] }}</th>
                <th>{{ analysis[a]['contribution_rank'] }}</th>
                <th>{{ analysis[a]['contribution_mail'] }}%({{ analysis[a]['mail_count'] }}件)</th>
                <th>{{ analysis[a]['contribution_schedule'] }}%({{ analysis[a]['schedule_count'] }}件)</th>
                <th>{{ analysis[a]['contribution_slack'] }}%({{ analysis[a]['slack_count'] }}件)</th>
                <th>{{ analysis[a]['contribution_zoom'] }}%({{ analysis[a]['zoom_count'] }}件)</th>
            </tr>
        {% endfor %}

    </table>

    <h2>貢献度を調整する</h2>
    <form action="/project?name={{ project_name }}" method="POST" enctype="multipart/form-data">
        <p>
            mail: <select name="mail">
                <option value={{ importance['mail'] }}>{{ importance['mail'] }}</option>
                <option value=1>1</option>
                <option value=2>2</option>
                <option value=3>3</option>
                <option value=4>4</option>
                <option value=4>5</option>
            </select>
        </p>
        <p>
            schedule: <select name="schedule">
                <option value={{ importance['schedule'] }}>{{ importance['schedule'] }}</option>
                <option value=1>1</option>
                <option value=2>2</option>
                <option value=3>3</option>
                <option value=4>4</option>
                <option value=4>5</option>
            </select>
        </p>
        <p>
            slack: <select name="slack">
                <option value={{ importance['slack'] }}>{{ importance['slack'] }}</option>
                <option value=1>1</option>
                <option value=2>2</option>
                <option value=3>3</option>
                <option value=4>4</option>
                <option value=4>5</option>
            </select>
        </p>
        <p>
            zoom: <select name="zoom">
                <option value={{ importance['zoom'] }}>{{ importance['zoom'] }}</option>
                <option value=1>1</option>
                <option value=2>2</option>
                <option value=3>3</option>
                <option value=4>4</option>
                <option value=4>5</option>
            </select>
        </p>
        <input type="submit" value="更新">
    </form>


{#    <h3>Gmail</h3>#}
{#    <canvas id="myPieChart"></canvas>#}
{#    <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.7.2/Chart.bundle.js"></script>#}
{#    <script>#}
{#      var ctx = document.getElementById("myPieChart");#}
{#      var names_str = "{{ names_str }}"#}
{#      var names = names_str.split(',')#}
{#      var datasets_mail = {{ data['gmail_data'] }}#}
{#      var myPieChart = new Chart(ctx, {#}
{#        type: 'pie',#}
{#        data: {#}
{#          labels: names,#}
{#          datasets: [{#}
              {#backgroundColor: [#}
              {#    "#BB5179",#}
              {#    "#FAFF67",#}
              {#    "#58A27C",#}
              {#    "#3C00FF"#}
              {#],#}
{#              data: datasets_mail#}
{#          }]#}
{#        },#}
{#        options: {#}
{#          title: {#}
{#            display: true,#}
{#            text: '関係しているGmailの数'#}
{#          }#}
{#        }#}
{#      });#}
{#    </script>#}
{##}
{#    <h3>Schedule</h3>#}
{#    <canvas id="PieChart"></canvas>#}
{#    <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.7.2/Chart.bundle.js"></script>#}
{#    <script>#}
{#      var ctx = document.getElementById("myPieChart");#}
{#      var names_str = "{{ names_str }}"#}
{#      var names = names_str.split(',')#}
{#      var datasets_schedule = {{ data['schedule_data'] }}#}
{#      var myPieChart2 = new Chart(ctx, {#}
{#        type: 'pie',#}
{#        data: {#}
{#          labels: names,#}
{#          datasets: [{#}
              {#backgroundColor: [#}
              {#    "#BB5179",#}
              {#    "#FAFF67",#}
              {#    "#58A27C",#}
              {#    "#3C00FF"#}
              {#],#}
{#              data: datasets_schedule#}
{#          }]#}
{#        },#}
{#        options: {#}
{#          title: {#}
{#            display: true,#}
{#            text: '関係しているGmailの数'#}
{#          }#}
{#        }#}
{#      });#}
{#    </script>#}



{#    <table border="1">#}
{#        <tr>#}
{#            <th>ID</th>#}
{#            <th>NAME</th>#}
{#            <th>DEPARTMENT</th>#}
{#            <th>MAIL</th>#}
{#            <th>SLACK_ID</th>#}
{#        </tr>#}
{#            {% for user in users %}#}
{#                <tr>#}
{#                    <td>{{ user['id'] }}</td>#}
{#                    <td>{{ user['name'] }}</td>#}
{#                    <td>{{ user['department'] }}</td>#}
{#                    <td>{{ user['mail'] }}</td>#}
{#                    <td>{{ user['slack_id'] }}</td>#}
{#                    <td><button onclick="location.href='user?id={{ user['id'] }}'">詳細</button></td>#}
{#                </tr>#}
{#            {% endfor %}#}
{#    </table>#}
{% endblock %}

flaskr/templates/main/top.html
{% extends "base.html" %}
{% block title %}
    トップ
{% endblock %}
{% block content %}
    <h1>トップメニュー</h1>
    <h3>目次</h3>
    <div>
        <span><a href="#1">従業員</a></span>
        <span><a href="#2">プロジェクト</a></span>
    </div>
    <h3 id="1">従業員一覧</h3>
    <table border="1">
        <tr>
            <th>ID</th>
            <th>NAME</th>
            <th>DEPARTMENT</th>
            <th>MAIL</th>
        </tr>
            {% for user in users %}
                <tr>
                    <td>{{ user['id'] }}</td>
                    <td>{{ user['name'] }}</td>
                    <td>{{ user['department'] }}</td>
                    <td>{{ user['mail'] }}</td>
                    <td><button onclick="location.href='user?id={{ user['id'] }}'">詳細</button></td>
                </tr>
            {% endfor %}
    </table>
    <h3 id="2">プロジェクト一覧</h3>
    <table border="1">
        <tr>
            <th>ID</th>
            <th>NAME</th>
        </tr>
            {% for project in projects %}
                <tr>
                    <td>{{ project['id'] }}</td>
                    <td>{{ project['name'] }}</td>
                    <td><button onclick="location.href='project?name={{ project['name'] }}'">分析</button></td>
                </tr>
            {% endfor %}
    </table>
{% endblock %}

flaskr/templates/main/user_detail.html
{% extends "base.html" %}
{% block title %}
    ユーザー詳細
{% endblock %}
{% block content %}
    <a href="{{url_for('main.top_menu')}}">トップメニュー</a>
    <h1>従業員情報</h1>
    <div>
        <span><a href="#1">スケジュール</a></span>
        <span><a href="#2">メール</a></span>
        <span><a href="#3">SLACK CHANEL</a></span>
        <span><a href="#4">SLACK MESSAGE</a></span>
        <span><a href="#5">ZOOMミーティング</a></span>
    </div>
    <h3>NO.{{ user.id }}
    <h2>{{ information.name }}</h2>
    <table border="1">
        <tr>
            <th>部署</th>
            <th>{{ information.department }}</th>
        </tr>
        <tr>
            <th>生年月日</th>
            <th>{{ information.birthday }}</th>
        </tr>
        <tr>
            <th>性別</th>
            <th>{{ information.sex }}</th>
        </tr>
        <tr>
            <th>メールアドレス</th>
            <th>{{ user.gmail }}</th>
        </tr>
        <tr>
            <th>SLACK_ID</th>
            <th>{{ user.slack_id }}</th>
        </tr>
    </table>

    <br>

    <h3 id="1">スケジュール</h3>
    <table border="1">
        <tr>
            <th>日時</th>
            <th>タイトル</th>
            <th>場所</th>
            <th>詳細</th>
            <th>リンク</th>
            <th>イベントID</th>
            <th>作成者</th>
            <th>作成日時</th>
            <th>更新日時</th>
        </tr>
        {% for s in schedule %}
            <tr>
                <th>{{ s.date }}</th>
                <th>{{ s.title }}</th>
                <th>{{ s.location }}</th>
                <th>{{ s.description }}</th>
                <th>{{ s.link }}</th>
                <th>{{ s.event_id }}</th>
                <th>{{ s.creator }}</th>
                <th>{{ s.event_created }}</th>
                <th>{{ s.event_updated }}</th>
            </tr>
        {%  endfor %}
    </table>

    <br>
    <h3 id="2">メール</h3>
    <table border="1">
        <tr>
            <th>日時</th>
            <th>タイトル</th>
            <th>送信者</th>
            <th>送信者アドレス</th>
            <th>本文</th>
        </tr>
        {% for m in mail %}
            <tr>
                <th>{{ m.date }}</th>
                <th>{{ m.subject }}</th>
                <th>{{ m.sender_name }}</th>
                <th>{{ m.sender_email }}</th>
                <th>{{ m.message }}</th>
            </tr>
        {%  endfor %}
    </table>

    <br>
    <h3 id="3">SLACK CHANNEL</h3>
    <table border="1">
        <tr>
            <th>CHANNEL_ID</th>
            <th>名前</th>
        </tr>
        {% for c in slack_channel %}
            <tr>
                <th>{{ c.channel_id }}</th>
                <th>{{ c.name }}</th>
            </tr>
        {%  endfor %}
    </table>

    <br>
    <h3 id="4">SLACK MESSAGE</h3>
    <table border="1">
        <tr>
            <th>日時</th>
            <th>チャンネル</th>
            <th>イベントID</th>
            <th>種別</th>
            <th>テキスト</th>
            <th>リアクション</th>
            <th>FILE_ID</th>
        </tr>
        {% for m in slack_message %}
            <tr>
                <th>{{ m.message_time }}</th>
                <th>{{ m.name }}</th>
                <th>{{ m.event_id }}</th>
                <th>{{ m.event_type }}</th>
                <th>{{ m.text }}</th>
                <th>{{ m.reaction }}</th>
                <th>{{ m.file_id }}</th>
            </tr>
        {%  endfor %}
    </table>

    <br>
    <h3 id="5">ZOOMミーティング</h3>
    <table border="1">
        <tr>
            <th>日時</th>
            <th>時間</th>
            <th>タイトル</th>
            <th>作成日時</th>
        </tr>
        {% for z in zoom_meeting %}
            <tr>
                <th>{{ z[2] }}</th>
                <th>{{ z[3] }}</th>
                <th>{{ z[1] }}</th>
                <th>{{ z[4] }}</th>
            </tr>
        {%  endfor %}
    </table>



{#    <h2>従業員一覧</h2>#}
{#    <table>#}
{#        <tr>#}
{#            <th>ID</th>#}
{#            <th>NAME</th>#}
{#            <th>DEPARTMENT</th>#}
{#            <th>MAIL</th>#}
{#            <th>SLACK_ID</th>#}
{#        </tr>#}
{#            {% for user in users %}#}
{#                <tr>#}
{#                    <td>{{ user['id'] }}</td>#}
{#                    <td>{{ user['name'] }}</td>#}
{#                    <td>{{ user['department'] }}</td>#}
{#                    <td>{{ user['mail'] }}</td>#}
{#                    <td>{{ user['slack_id'] }}</td>#}
{#                    <td><a href="sample.html">詳細</a></td>#}
{#                </tr>#}
{#            {% endfor %}#}
{#        </table>#}
{% endblock %}